<a href="https://colab.research.google.com/github/MdShajalalsojib/Machine-Learning-Lab/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('titanic_train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
len(df.columns)

12

In [11]:
df[ 'Age' ]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [12]:
df[['Age']] # DataFrame ...

      Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

In [13]:
# sum of NaN in the age column
df['Age'].isnull().sum()

np.int64(177)

In [14]:
len(df)

891

In [15]:
df['Age'] = df['Age'].fillna(int(df['Age'].mean()))

In [16]:
df['Age'].isnull().sum()

np.int64(0)

In [18]:
# drop a column
# df = df.drop('name',axis=1)
df.drop('Name',axis=1,inplace=True)

In [19]:
len(df.columns)

11

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [21]:
df.drop(['Cabin','Fare','Embarked'],axis=1,inplace=True)

In [22]:
len(df.columns)

8

In [23]:
df.describe()

       PassengerId    Survived      Pclass         Age       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.560236    0.523008    0.381594
std     257.353842    0.486592    0.836071   13.005010    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   22.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000   29.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000   35.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000

In [24]:
import numpy as np

df_demo = pd.DataFrame(
    {
        'key1': ['k1v1','k1v2','k1v3'],
        'key2': ['k2v1',np.nan,'k3v3'],
    }
,)

df_demo

   key1  key2
0  k1v1  k2v1
1  k1v2   NaN
2  k1v3  k3v3

In [25]:
df = df.dropna(axis=0)

In [26]:
len(df)

891

In [27]:
df['Age'].values

array([22.  , 38.  , 26.  , 35.  , 35.  , 29.  , 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 29.  ,
       31.  , 29.  , 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  , 29.  ,
       19.  , 29.  , 29.  , 40.  , 29.  , 29.  , 66.  , 28.  , 42.  ,
       29.  , 21.  , 18.  , 14.  , 40.  , 27.  , 29.  ,  3.  , 19.  ,
       29.  , 29.  , 29.  , 29.  , 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  , 29.  , 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  , 29.  , 29.  , 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  , 29.  , 29.  ,  0.83, 30.  , 22.  ,
       29.  , 29.  , 28.  , 17.  , 33.  , 16.  , 29.  , 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  , 29.  , 71.  , 23.  , 34.  ,
       34.  , 28.  , 29.  , 21.  , 33.  , 37.  , 28.  , 21.  , 29.  ,
       38.  , 29.  , 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  , 29.  , 32.5 , 32.5 , 54.  , 12.  ,
       29.  , 24.  , 29.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  ,
       23.  , 19.  , 37.  , 16.  , 24.  , 29.  , 22.  , 24.  , 19.  ,
       18.  , 19.  , 27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 ,
       40.5 , 29.  , 51.  , 16.  , 30.  , 29.  , 29.  , 44.  , 40.  ,
       26.  , 17.  ,  1.  ,  9.  , 29.  , 45.  , 29.  , 28.  , 61.  ,
        4.  ,  1.  , 21.  , 56.  , 18.  , 29.  , 50.  , 30.  , 36.  ,
       29.  , 29.  ,  9.  ,  1.  ,  4.  , 29.  , 29.  , 45.  , 40.  ,
       36.  , 32.  , 19.  , 19.  ,  3.  , 44.  , 58.  , 29.  , 42.  ,
       29.  , 24.  , 28.  , 29.  , 34.  , 45.5 , 18.  ,  2.  , 32.  ,
       26.  , 16.  , 40.  , 24.  , 35.  , 22.  , 30.  , 29.  , 31.  ,
       27.  , 42.  , 32.  , 30.  , 16.  , 27.  , 51.  , 29.  , 38.  ,
       22.  , 19.  , 20.5 , 18.  , 29.  , 35.  , 29.  , 59.  ,  5.  ,
       24.  , 29.  , 44.  ,  8.  , 19.  , 33.  , 29.  , 29.  , 29.  ,
       22.  , 30.  , 44.  , 25.  , 24.  , 37.  , 54.  , 29.  , 29.  ,
       62.  , 30.  , 41.  , 29.  , 29.  , 30.  , 35.  , 50.  , 29.  ,
        3.  , 52.  , 40.  , 29.  , 36.  , 16.  , 25.  , 58.  , 35.  ,
       29.  , 25.  , 41.  , 37.  , 29.  , 63.  , 45.  , 29.  ,  7.  ,
       35.  , 65.  , 28.  , 16.  , 19.  , 29.  , 33.  , 30.  , 22.  ,
       42.  , 22.  , 26.  , 19.  , 36.  , 24.  , 24.  , 29.  , 23.5 ,
        2.  , 29.  , 50.  , 29.  , 29.  , 19.  , 29.  , 29.  ,  0.92,
       29.  , 17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 43.  ,
       26.  , 24.  , 54.  , 31.  , 40.  , 22.  , 27.  , 30.  , 22.  ,
       29.  , 36.  , 61.  , 36.  , 31.  , 16.  , 29.  , 45.5 , 38.  ,
       16.  , 29.  , 29.  , 29.  , 41.  , 45.  , 45.  ,  2.  , 24.  ,
       28.  , 25.  , 36.  , 24.  , 40.  , 29.  ,  3.  , 42.  , 23.  ,
       29.  , 15.  , 25.  , 29.  , 28.  , 22.  , 38.  , 29.  , 29.  ,
       40.  , 29.  , 45.  , 35.  , 29.  , 30.  , 60.  , 29.  , 29.  ,
       24.  , 25.  , 18.  , 19.  , 22.  ,  3.  , 29.  , 22.  , 27.  ,
       20.  , 19.  , 42.  ,  1.  , 32.  , 35.  , 29.  , 18.  ,  1.  ,
       36.  , 29.  , 17.  , 36.  , 21.  , 28.  , 23.  , 24.  , 22.  ,
       31.  , 46.  , 23.  , 28.  , 39.  , 26.  , 21.  , 28.  , 20.  ,
       34.  , 51.  ,  3.  , 21.  , 29.  , 29.  , 29.  , 33.  , 29.  ,
       44.  , 29.  , 34.  , 18.  , 30.  , 10.  , 29.  , 21.  , 29.  ,
       28.  , 18.  , 29.  , 28.  , 19.  , 29.  , 32.  , 28.  , 29.  ,
       42.  , 17.  , 50.  , 14.  , 21.  , 24.  , 64.  , 31.  , 45.  ,
       20.  , 25.  , 28.  , 29.  ,  4.  , 13.  , 34.  ,  5.  , 52.  ,
       36.  , 29.  , 30.  , 49.  , 29.  , 29.  , 65.  , 29.  , 50.  ,
       29.  , 48.  , 34.  , 47.  , 48.  , 29.  , 38.  , 29.  , 56.  ,
       29.  ,  0.75, 29.  , 38.  , 33.  , 23.  , 22.  , 29.  , 34.  ,
       29.  , 22.  ,  2.  ,  9.  , 29.  , 50.  , 63.  , 25.  , 29.  ,
       35.  , 58.  , 30.  ,  9.  , 29.  , 21.  , 55.  , 71.  , 21.  ,
       29.  , 54.  , 29.  , 25.  , 24.  , 17.  , 21.  , 29.  , 37.  ,
       16.  , 18.  , 33.  , 29.  , 28.  , 26.  , 29.  , 29.  , 36.  ,
       54.  , 24.  , 47.  , 34.  , 29.  , 36.  , 32.  , 30.  , 22.  ,
       29.  , 44.  , 29.  , 40.5 , 50.  , 29.  , 39.  , 23.  ,  2.  ,
       29.  , 17.  , 29.  , 30.  ,  7.  , 45.  , 30.  , 29.  , 22.  ,
       36.  ,  9.  , 11.  , 32.  , 50.  , 64.  , 19.  , 29.  , 33.  ,
        8.  , 17.  , 27.  , 29.  , 22.  , 22.  , 62.  , 48.  , 29.  ,
       39.  , 36.  , 29.  , 40.  , 28.  , 29.  , 29.  , 24.  , 19.  ,
       29.  , 29.  , 32.  , 62.  , 53.  , 36.  , 29.  , 16.  , 19.  ,
       34.  , 39.  , 29.  , 32.  , 25.  , 39.  , 54.  , 36.  , 29.  ,
       18.  , 47.  , 60.  , 22.  , 29.  , 35.  , 52.  , 47.  , 29.  ,
       37.  , 36.  , 29.  , 49.  , 29.  , 49.  , 24.  , 29.  , 29.  ,
       44.  , 35.  , 36.  , 30.  , 27.  , 22.  , 40.  , 39.  , 29.  ,
       29.  , 29.  , 35.  , 24.  , 34.  , 26.  ,  4.  , 26.  , 27.  ,
       42.  , 20.  , 21.  , 21.  , 61.  , 57.  , 21.  , 26.  , 29.  ,
       80.  , 51.  , 32.  , 29.  ,  9.  , 28.  , 32.  , 31.  , 41.  ,
       29.  , 20.  , 24.  ,  2.  , 29.  ,  0.75, 48.  , 19.  , 56.  ,
       29.  , 23.  , 29.  , 18.  , 21.  , 29.  , 18.  , 24.  , 29.  ,
       32.  , 23.  , 58.  , 50.  , 40.  , 47.  , 36.  , 20.  , 32.  ,
       25.  , 29.  , 43.  , 29.  , 40.  , 31.  , 70.  , 31.  , 29.  ,
       18.  , 24.5 , 18.  , 43.  , 36.  , 29.  , 27.  , 20.  , 14.  ,
       60.  , 25.  , 14.  , 19.  , 18.  , 15.  , 31.  ,  4.  , 29.  ,
       25.  , 60.  , 52.  , 44.  , 29.  , 49.  , 42.  , 18.  , 35.  ,
       18.  , 25.  , 26.  , 39.  , 45.  , 42.  , 22.  , 29.  , 24.  ,
       29.  , 48.  , 29.  , 52.  , 19.  , 38.  , 27.  , 29.  , 33.  ,
        6.  , 17.  , 34.  , 50.  , 27.  , 20.  , 30.  , 29.  , 25.  ,
       25.  , 29.  , 11.  , 29.  , 23.  , 23.  , 28.5 , 48.  , 35.  ,
       29.  , 29.  , 29.  , 36.  , 21.  , 24.  , 31.  , 70.  , 16.  ,
       30.  , 19.  , 31.  ,  4.  ,  6.  , 33.  , 23.  , 48.  ,  0.67,
       28.  , 18.  , 34.  , 33.  , 29.  , 41.  , 20.  , 36.  , 16.  ,
       51.  , 29.  , 30.5 , 29.  , 32.  , 24.  , 48.  , 57.  , 29.  ,
       54.  , 18.  , 29.  ,  5.  , 29.  , 43.  , 13.  , 17.  , 29.  ,
       29.  , 25.  , 25.  , 18.  ,  8.  ,  1.  , 46.  , 29.  , 16.  ,
       29.  , 29.  , 25.  , 39.  , 49.  , 31.  , 30.  , 30.  , 34.  ,
       31.  , 11.  ,  0.42, 27.  , 31.  , 39.  , 18.  , 39.  , 33.  ,
       26.  , 39.  , 35.  ,  6.  , 30.5 , 29.  , 23.  , 31.  , 43.  ,
       10.  , 52.  , 27.  , 38.  , 27.  ,  2.  , 29.  , 29.  ,  1.  ,
       29.  , 62.  , 15.  ,  0.83, 29.  , 23.  , 18.  , 39.  , 21.  ,
       29.  , 32.  , 29.  , 20.  , 16.  , 30.  , 34.5 , 17.  , 42.  ,
       29.  , 35.  , 28.  , 29.  ,  4.  , 74.  ,  9.  , 16.  , 44.  ,
       18.  , 45.  , 51.  , 24.  , 29.  , 41.  , 21.  , 48.  , 29.  ,
       24.  , 42.  , 27.  , 31.  , 29.  ,  4.  , 26.  , 47.  , 33.  ,
       47.  , 28.  , 15.  , 20.  , 19.  , 29.  , 56.  , 25.  , 33.  ,
       22.  , 28.  , 25.  , 39.  , 27.  , 19.  , 29.  , 26.  , 32.  ])

In [30]:
# unique values
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [31]:
# unique values
df['Survived'].unique()

array([0, 1])

In [32]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket'],
      dtype='object')

In [33]:
df['name'] = ['a' for i in range(len(df))]

In [34]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,name
0,1,0,3,male,22.0,1,0,A/5 21171,a
1,2,1,1,female,38.0,1,0,PC 17599,a
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,a
3,4,1,1,female,35.0,1,0,113803,a
4,5,0,3,male,35.0,0,0,373450,a
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,a
887,888,1,1,female,19.0,0,0,112053,a
888,889,0,3,female,29.0,1,2,W./C. 6607,a
889,890,1,1,male,26.0,0,0,111369,a
890,891,0,3,male,32.0,0,0,370376,a

In [35]:
# iloc means integer location
df.iloc[0]

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                 22.0
SibSp                  1
Parch                  0
Ticket         A/5 21171
name                   a
Name: 0, dtype: object

In [39]:
# apply function to a column
def fun(value):
    # print(type(value))
    if value<18:
        return 'child'
    else:
        return 'adult'

df['Age_description'] = df['Age'].apply(fun)
# df.drop('Name',axis=1) # This line is causing the error because 'Name' column was already dropped

In [40]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,name,Age_description
0,1,0,3,male,22.0,1,0,A/5 21171,a,adult
1,2,1,1,female,38.0,1,0,PC 17599,a,adult
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,a,adult
3,4,1,1,female,35.0,1,0,113803,a,adult
4,5,0,3,male,35.0,0,0,373450,a,adult
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,a,adult
887,888,1,1,female,19.0,0,0,112053,a,adult
888,889,0,3,female,29.0,1,2,W./C. 6607,a,adult
889,890,1,1,male,26.0,0,0,111369,a,adult
890,891,0,3,male,32.0,0,0,370376,a,adult

In [41]:
# basic statistics
df['Age'].min()
df['Age'].max()
df['Age'].std()

13.005010341761817

In [42]:
# !pip install scikit-learn
# Importing necessary libraries for encoding categorical variables
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

In [43]:
# label encoding
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

In [44]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,name,Age_description
0,1,0,3,1,22.0,1,0,A/5 21171,a,adult
1,2,1,1,0,38.0,1,0,PC 17599,a,adult
2,3,1,3,0,26.0,0,0,STON/O2. 3101282,a,adult
3,4,1,1,0,35.0,1,0,113803,a,adult
4,5,0,3,1,35.0,0,0,373450,a,adult
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,27.0,0,0,211536,a,adult
887,888,1,1,0,19.0,0,0,112053,a,adult
888,889,0,3,0,29.0,1,2,W./C. 6607,a,adult
889,890,1,1,1,26.0,0,0,111369,a,adult
890,891,0,3,1,32.0,0,0,370376,a,adult

In [45]:
# oe = OrdinalEncoder()
# df['sex'] = oe.fit_transform(df['sex'])

In [47]:
df.Age_description.unique()

array(['adult', 'child'], dtype=object)

In [48]:
# one-hot encoding for age_description it removes the bias of the age_description column
ohe = OneHotEncoder()
encoded = ohe.fit_transform(df[['Age_description']])
# encoded.toarray()

In [49]:
# to get the feature names after one-hot encoding
ohe.get_feature_names_out()

array(['Age_description_adult', 'Age_description_child'], dtype=object)

In [50]:
# Create a new DataFrame with the one-hot encoded features
df_new = pd.DataFrame(
encoded.toarray(),columns=ohe.get_feature_names_out()
)

In [51]:
df_new

     Age_description_adult  Age_description_child
0                      1.0                    0.0
1                      1.0                    0.0
2                      1.0                    0.0
3                      1.0                    0.0
4                      1.0                    0.0
..                     ...                    ...
886                    1.0                    0.0
887                    1.0                    0.0
888                    1.0                    0.0
889                    1.0                    0.0
890                    1.0                    0.0

[891 rows x 2 columns]

In [54]:
# x - x_min() / (x_max - x_min())
# min-max normalization
df['SibSp'] = (df['SibSp'] - df['SibSp'].min())/(df['SibSp'].max() - df['SibSp'].min())

In [55]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,name,Age_description
0,1,0,3,1,22.0,0.125,0,A/5 21171,a,adult
1,2,1,1,0,38.0,0.125,0,PC 17599,a,adult
2,3,1,3,0,26.0,0.000,0,STON/O2. 3101282,a,adult
3,4,1,1,0,35.0,0.125,0,113803,a,adult
4,5,0,3,1,35.0,0.000,0,373450,a,adult
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,27.0,0.000,0,211536,a,adult
887,888,1,1,0,19.0,0.000,0,112053,a,adult
888,889,0,3,0,29.0,0.125,2,W./C. 6607,a,adult
889,890,1,1,1,26.0,0.000,0,111369,a,adult
890,891,0,3,1,32.0,0.000,0,370376,a,adult

In [57]:
# filter rows based on a condition
df[df['SibSp']>=1]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,name,Age_description
159,160,0,3,1,29.0,1.0,2,CA. 2343,a,adult
180,181,0,3,0,29.0,1.0,2,CA. 2343,a,adult
201,202,0,3,1,29.0,1.0,2,CA. 2343,a,adult
324,325,0,3,1,29.0,1.0,2,CA. 2343,a,adult
792,793,0,3,0,29.0,1.0,2,CA. 2343,a,adult
846,847,0,3,1,29.0,1.0,2,CA. 2343,a,adult
863,864,0,3,0,29.0,1.0,2,CA. 2343,a,adult