<a href="https://colab.research.google.com/github/MdShajalalsojib/Machine-Learning-Lab/blob/main/Lab_Report_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pdp

In [4]:
so = pdp.read_csv('bangla_spam.csv')

In [5]:
so.head()

   type                                               text
0  spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1  spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2   ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3  spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4   ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...

In [6]:
so.head(10)

   type                                               text
0  spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1  spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2   ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3  spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4   ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...
5  spam  আপনার ইমেইল যাচাই করুন এবং ২০০০ টাকা বোনাস জিতুন!
6  spam         নতুন গ্যাজেট কিনুন এবং ১০% ক্যাশব্যাক পান!
7  spam  আপনার মোবাইল রিচার্জ করুন এবং ১৫% ক্যাশব্যাক পান!
8  spam   বিশেষ ছাড়! সব পণ্যের উপর ৯৫% পর্যন্ত ডিসকাউন্ট!
9  spam                আজই ক্লিক করুন এবং ৫০০০ টাকা জিতুন!

In [7]:
import re

def clean_text(text):
    text = re.sub(r'[^\u0980-\u09FF\s]', '', str(text))
    return text

so['clean_text'] = so['text'].apply(clean_text)

so['tokens'] = so['clean_text'].apply(lambda x: x.split())

stopwords = ['আমি','তুমি','এই','ওই','সে','এটা']
so['tokens'] = so['tokens'].apply(lambda x: [word for word in x if word not in stopwords])

def stemming(words):
    return [word[:-1] if len(word) > 4 else word for word in words]

so['final'] = so['tokens'].apply(stemming)

so['final_text'] = so['final'].apply(lambda x: " ".join(x))

In [14]:
so

,type,text,clean_text,tokens,final,final_text
0,spam,এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...,এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...,"[মেসেজটি, শেয়ার, করুন, এবং, জিতে, নিন, আকর্ষণ...","[মেসেজট, শেয়া, করুন, এবং, জিতে, নিন, আকর্ষণীয...",মেসেজট শেয়া করুন এবং জিতে নিন আকর্ষণীয পুরস্কা
1,spam,আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...,আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...,"[আপনার, বন্ধুদের, রেফার, করুন, এবং, প্রতি, রেফ...","[আপনা, বন্ধুদে, রেফা, করুন, এবং, প্রত, রেফারেল...",আপনা বন্ধুদে রেফা করুন এবং প্রত রেফারেল ২০০ টা...
2,ham,ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...,ট্রানজ্যাকশন নম্বর টাকা রিচার্জটি সফল হয়েছে ...,"[ট্রানজ্যাকশন, নম্বর, টাকা, রিচার্জটি, সফল, হয়...","[ট্রানজ্যাকশ, নম্ব, টাকা, রিচার্জট, সফল, হয়েছ,...",ট্রানজ্যাকশ নম্ব টাকা রিচার্জট সফল হয়েছ আপনা ব...
3,spam,নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...,নতুন অফার সীমিত সময়ের জন্য পণ্যের উপর ৯০ পর্য...,"[নতুন, অফার, সীমিত, সময়ের, জন্য, পণ্যের, উপর,...","[নতুন, অফার, সীমি, সময়ে, জন্য, পণ্যে, উপর, ৯০...",নতুন অফার সীমি সময়ে জন্য পণ্যে উপর ৯০ পর্যন্ ...
4,ham,নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...,নববর্ষের শুভেচ্ছা আল্লাহ আপনার সকল কষ্ট দূর কর...,"[নববর্ষের, শুভেচ্ছা, আল্লাহ, আপনার, সকল, কষ্ট,...","[নববর্ষে, শুভেচ্ছ, আল্লা, আপনা, সকল, কষ্ট, দূর...",নববর্ষে শুভেচ্ছ আল্লা আপনা সকল কষ্ট দূর করে আপ...
...,...,...,...,...,...,...
2597,spam,প্রতিদিন ১০০ টাকা জিততে চান? এখনই অংশগ্রহণ করুন!,প্রতিদিন ১০০ টাকা জিততে চান এখনই অংশগ্রহণ করুন,"[প্রতিদিন, ১০০, টাকা, জিততে, চান, এখনই, অংশগ্র...","[প্রতিদি, ১০০, টাকা, জিতত, চান, এখনই, অংশগ্রহ,...",প্রতিদি ১০০ টাকা জিতত চান এখনই অংশগ্রহ করুন
2598,spam,মোবাইল অ্যাপ ডাউনলোড করুন এবং ৫০০ টাকা বোনাস পান!,মোবাইল অ্যাপ ডাউনলোড করুন এবং ৫০০ টাকা বোনাস পান,"[মোবাইল, অ্যাপ, ডাউনলোড, করুন, এবং, ৫০০, টাকা,...","[মোবাই, অ্যা, ডাউনলো, করুন, এবং, ৫০০, টাকা, বো...",মোবাই অ্যা ডাউনলো করুন এবং ৫০০ টাকা বোনা পান
2599,spam,"নতুন গ্রাহকদের জন্য বিশেষ অফার, আজই উপভোগ করুন!",নতুন গ্রাহকদের জন্য বিশেষ অফার আজই উপভোগ করুন,"[নতুন, গ্রাহকদের, জন্য, বিশেষ, অফার, আজই, উপভো...","[নতুন, গ্রাহকদে, জন্য, বিশে, অফার, আজই, উপভো, ...",নতুন গ্রাহকদে জন্য বিশে অফার আজই উপভো করুন
2600,spam,আপনার অ্যাকাউন্ট আপগ্রেড করুন এবং এক্সক্লুসিভ ...,আপনার অ্যাকাউন্ট আপগ্রেড করুন এবং এক্সক্লুসিভ ...,"[আপনার, অ্যাকাউন্ট, আপগ্রেড, করুন, এবং, এক্সক্...","[আপনা, অ্যাকাউন্, আপগ্রে, করুন, এবং, এক্সক্লুস...",আপনা অ্যাকাউন্ আপগ্রে করুন এবং এক্সক্লুসি সুবি...
2601,spam,বিশেষ ছাড়! ২৪ ঘন্টার মধ্যে অর্ডার করুন এবং ৩০...,বিশেষ ছাড় ২৪ ঘন্টার মধ্যে অর্ডার করুন এবং ৩০ ...,"[বিশেষ, ছাড়, ২৪, ঘন্টার, মধ্যে, অর্ডার, করুন,...","[বিশে, ছাড়, ২৪, ঘন্টা, মধ্য, অর্ডা, করুন, এবং...",বিশে ছাড় ২৪ ঘন্টা মধ্য অর্ডা করুন এবং ৩০ ডিসক...

## TF--IDF (Multaple word to number convert)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X = tfidf.fit_transform(so['final_text'])

## TF--IDF (word to number convert)

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(so['type'])

In [10]:
from sklearn.model_selection import train_test_split

x = so['final_text']
y = so['type']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2)

## Model Apply

In [11]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

## Score

In [13]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9328214971209213